In [1]:
# TASK 1 - Create basic arrays
#
# Write make_arrays(): return a dict with five keys:
#   zeros: np.zeros((3, 4))
#   ones: np.ones((2, 3, 4))
#   arange: np.arange(0, 10, 2)
#   random: np.random.randn(3, 3)
#   from_list: np.array([[1, 2], [3, 4]])
#
# Why it matters: every weight matrix in an LLM starts as one of these calls.


import numpy as np


def make_arrays():
    results = {}
    results["zeros"] = np.zeros((3,4))
    results["ones"] = np.ones((2,3,4))
    results["random"] = np.random.randn(3,3)
    results["from_list"] = np.array([[1,2],[3,4]])
    results["arange"] =  np.array([0, 2, 4, 6, 8])

    return results


result = make_arrays()
assert result["zeros"].shape == (3, 4)
assert result["ones"].shape == (2, 3, 4)
assert np.array_equal(result["arange"], np.array([0, 2, 4, 6, 8]))
assert result["random"].shape == (3, 3)
assert np.array_equal(result["from_list"], np.array([[1, 2], [3, 4]]))
print("Task 1 passed")

Task 1 passed


In [2]:
arr = np.zeros((2, 3, 4))
print(arr)
print(arr.ndim)   # 3

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [3]:
# TASK 2 - Shape inspection
#
# Write describe(x): return dict with shape, dtype, ndim.
# These three show up in EVERY PyTorch error you will ever see.


def describe(x):
    info = {}
    info["shape"] = x.shape
    info["dtype"] = x.dtype
    info["ndim"] = x.ndim

    return info


info = describe(np.array([[1.0, 2.0], [3.0, 4.0]]))
assert info["shape"] == (2, 2)
assert info["dtype"] == np.float64
assert info["ndim"] == 2
print("Task 2 passed")

Task 2 passed


In [9]:
# TASK 3 - Indexing and slicing
#
# Write slice_demo(x): x is (4, 5). Return dict with:
#   row0: first row, shape (5,)
#   col0: first column, shape (4,)
#   top_left: top-left 2x2, shape (2, 2)
#   every_other_row: rows 0 and 2, shape (2, 5)
#
# Pattern: x[i] row, x[:, j] column, x[a:b, c:d] block, x[::2, :] stride.


def slice_demo(x):
    out = {
        "row0" : x[0,:],
        "col0" : x[:,0],
        "top_left": x[:2, :2],
        "every_other_row":  x[::2, :]
    }

    return out


x = np.arange(20).reshape(4, 5)
print(x)
out = slice_demo(x)
assert np.array_equal(out["row0"], np.array([0, 1, 2, 3, 4]))
assert np.array_equal(out["col0"], np.array([0, 5, 10, 15]))
assert np.array_equal(out["top_left"], np.array([[0, 1], [5, 6]]))
assert np.array_equal(out["every_other_row"], np.array([[0, 1, 2, 3, 4], [10, 11, 12, 13, 14]]))
print("Task 3 passed")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Task 3 passed


In [15]:
# TASK 4 - Reshape and flatten
#
# Write reshape_demo(x): x is flat length 12. Return:
#   as_3x4: (3, 4), as_2x6: (2, 6), as_2x2x3: (2, 2, 3), flat: (12,)
#
# reshape is a VIEW, flatten is a COPY.


def reshape_demo(x):
    out = {
        "as_3x4" : x.reshape(3,4),
        "as_2x6" : x.reshape(2,6),
        "as_2x2x3" : x.reshape(2,2,3),
        "flat": x.reshape(12,)
    }

    return out


x = np.arange(12)
print(x.shape)
out = reshape_demo(x)
assert out["as_3x4"].shape == (3, 4)
assert out["as_2x6"].shape == (2, 6)
assert out["as_2x2x3"].shape == (2, 2, 3)
assert out["flat"].shape == (12,)
print("Task 4 passed")

(12,)
Task 4 passed


In [17]:
# TASK 5 - Transpose
#
# Write transpose_demo(x): x is (2, 3). Return T (3, 2),
# swap via transpose(1, 0) (3, 2), perm_012 via transpose(0, 1) (2, 3).
#
# Why: attention does Q @ K.T constantly.


def transpose_demo(x):
    out = {
        "T" : x.T ,
        "swap"  : np.swapaxes(x,0,1),
        'perm_012': x.transpose(0, 1) 
    }

    return out


x = np.array([[1, 2, 3], [4, 5, 6]])
out = transpose_demo(x)
assert out["T"].shape == (3, 2)
assert out["swap"].shape == (3, 2)
assert out["perm_012"].shape == (2, 3)
print("Task 5 passed")

Task 5 passed


In [ ]:
# TASK 6 - Matrix multiplication
#
# Write matmul_demo(A, B): A (2, 3), B (3, 4). Return:
#   at_b: A @ B (2, 4), dot: np.dot(A, B) (2, 4), BT: A @ B.T (2, 3).
#
# Key rule: (a, b) @ (b, c) -> (a, c). Inner dims must match.
# Single most important shape rule in ML.


def matmul_demo(A, B):
    ...


A = np.random.randn(2, 3)
B = np.random.randn(3, 4)
out = matmul_demo(A, B)
assert out["at_b"].shape == (2, 4)
assert out["dot"].shape == (2, 4)
assert out["BT"].shape == (2, 3)
print("Task 6 passed")

In [ ]:
# TASK 7 - Elementwise ops
#
# Write elementwise(x): return scaled (x*2.5), shifted (x+10),
# neg (-x), squared (x**2). No shape change.


def elementwise(x):
    ...


x = np.array([[1.0, -2.0], [3.0, -4.0], [0.5, 2.5]])
out = elementwise(x)
assert np.array_equal(out["scaled"], x * 2.5)
assert np.array_equal(out["shifted"], x + 10)
assert np.array_equal(out["neg"], -x)
assert np.array_equal(out["squared"], x ** 2)
print("Task 7 passed")

In [ ]:
# TASK 8 - Reductions with axis + keepdims
#
# Write reduce_demo(x): x is (3, 4). Return:
#   sum_all: scalar, sum_axis0: (4,), mean_all: scalar,
#   max_all: scalar, argmax: flat index, sum_keep: (3, 1) via keepdims.
#
# axis=0 collapses rows, axis=1 collapses cols.
# keepdims keeps the dim as size 1 so broadcasting still works.


def reduce_demo(x):
    ...


x = np.array([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]])
out = reduce_demo(x)
assert out["sum_all"] == 78.0
assert np.array_equal(out["sum_axis0"], np.array([15.0, 18.0, 21.0, 24.0]))
assert out["mean_all"] == 6.5
assert out["max_all"] == 12.0
assert out["argmax"] == 11
assert out["sum_keep"].shape == (3, 1)
print("Task 8 passed")

In [ ]:
# TASK 9 - Broadcasting
#
# Write broadcast_demo(x): x is (3, 4). Return:
#   row_add: x + [10, 20, 30, 40], col_add: x + [[1], [2], [3]], scale: x * [0.5].
#
# Rule: shapes align from the RIGHT. Dims match if equal or one is 1.
# (3, 4) + (4,) -> (4,) treated as (1, 4), stretched to (3, 4).


def broadcast_demo(x):
    ...


x = np.array([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]])
out = broadcast_demo(x)
assert np.array_equal(out["row_add"], x + np.array([10, 20, 30, 40]))
assert np.array_equal(out["col_add"], x + np.array([[1], [2], [3]]))
assert np.array_equal(out["scale"], x * np.array([0.5]))
print("Task 9 passed")

In [ ]:
# TASK 10 - Softmax by hand (stable)
#
# Write softmax(x): 1-D logits -> probs summing to 1.
# Recipe: subtract max, exp, divide by sum.
# You will reuse this INSIDE attention. Memorize it.


def softmax(x):
    ...


probs = softmax(np.array([1.0, 2.0, 3.0]))
assert probs.shape == (3,)
assert np.isclose(probs.sum(), 1.0)
assert probs[2] > probs[1] > probs[0]
e = np.exp(np.array([1.0, 2.0, 3.0]) - 3.0)
assert np.allclose(probs, e / e.sum())
print("Task 10 passed")

In [ ]:
# TASK 11 - Batch softmax (axis matters)
#
# Write softmax_rows(X): X is (batch, features). Softmax EACH row
# independently so every row sums to 1.
#
# Why: attention applies softmax along LAST axis of (batch, seq, seq).
# Hint: keepdims=True so division broadcasts correctly.


def softmax_rows(X):
    ...


X = np.array([[1.0, 2.0, 3.0], [10.0, 0.0, 0.0]])
out = softmax_rows(X)
assert out.shape == (2, 3)
assert np.allclose(out.sum(axis=1), np.array([1.0, 1.0]))
assert out[1, 0] > 0.99
print("Task 11 passed")

In [ ]:
# TASK 12 - Dot product = similarity (attention scores)
#
# Write scores(q, K): q is (d,), K is (n, d). Return (n,) where
# entry i = dot(q, K[i]). Bigger = more similar.
#
# This IS the first half of attention: Q @ K.T.
# Shapes: (n, d) @ (d,) -> (n,).


def scores(q, K):
    ...


q = np.array([1.0, 0.0])
K = np.array([[1.0, 0.0], [0.0, 1.0], [-1.0, 0.0]])
s = scores(q, K)
assert s.shape == (3,)
assert np.allclose(s, np.array([1.0, 0.0, -1.0]))
print("Task 12 passed")

In [ ]:
# TASK 13 - Boolean masking + where (padding / causal mask)
#
# Write mask_fill(logits, mask, fill=-1e9):
#   logits (4,), mask is bool (4,) True = keep, False = block.
#   Return array where blocked positions are `fill`.
#
# Why: transformers mask padding + future tokens before softmax.
# Pattern: np.where(cond, a, b).


def mask_fill(logits, mask, fill=-1e9):
    ...


logits = np.array([1.0, 2.0, 3.0, 4.0])
mask = np.array([True, True, False, False])
out = mask_fill(logits, mask)
assert out.shape == (4,)
assert out[0] == 1.0 and out[1] == 2.0
assert out[2] < -1e8 and out[3] < -1e8
print("Task 13 passed")

In [ ]:
# TASK 14 - Embedding lookup (word -> id -> vector)
#
# Write lookup(W, ids): W is (vocab, d), ids is (n,) of ints.
# Return (n, d) where row i = W[ids[i]].
#
# This IS §3.1 input embeddings. Advanced integer indexing.
# Shapes: W (5, 4), ids (3,) -> (3, 4).


def lookup(W, ids):
    ...


W = np.arange(20).reshape(5, 4)
ids = np.array([0, 2, 4])
out = lookup(W, ids)
assert out.shape == (3, 4)
assert np.array_equal(out[0], W[0])
assert np.array_equal(out[1], W[2])
assert np.array_equal(out[2], W[4])
print("Task 14 passed")

In [ ]:
# TASK 15 - Batch handling: expand, squeeze, concat
#
# Write batch_demo(a, b): a, b are (d,) vectors. Return dict:
#   stacked: shape (2, d) via np.stack
#   expanded: a with shape (1, d) via np.expand_dims
#   squeezed: expanded squeezed back to (d,) via np.squeeze
#   catted: concat stacked with itself on axis 0 -> (4, d)
#
# Why: batching = stacking single examples. Squeeze/expand fix rank mismatches.


def batch_demo(a, b):
    ...


a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])
out = batch_demo(a, b)
assert out["stacked"].shape == (2, 3)
assert out["expanded"].shape == (1, 3)
assert out["squeezed"].shape == (3,)
assert out["catted"].shape == (4, 3)
print("Task 15 passed")

In [ ]:
# TASK 16 - Cross-entropy loss (what pre-training minimizes)
#
# Write ce_loss(probs, true_id): probs (V,) sum to 1, true_id int.
# Return scalar -log(probs[true_id]). Add 1e-9 inside log for safety.
#
# Why: every LLM training step is this number going down.
# Shapes: (V,) + int -> scalar.


def ce_loss(probs, true_id):
    ...


probs = np.array([0.1, 0.7, 0.2])
assert np.isclose(ce_loss(probs, 1), -np.log(0.7))
assert ce_loss(np.array([0.9, 0.05, 0.05]), 0) < ce_loss(np.array([0.34, 0.33, 0.33]), 0)
print("Task 16 passed")

In [ ]:
# TASK 17 - Seed + reproducibility
#
# Write seeded_rand(seed): set np.random.seed(seed), return np.random.randn(2, 2).
#
# Why: torch.manual_seed is the same idea. Same seed -> same numbers, always.


def seeded_rand(seed):
    ...


assert np.array_equal(seeded_rand(0), seeded_rand(0))
assert not np.array_equal(seeded_rand(0), seeded_rand(1))
print("Task 17 passed")

In [ ]:
# TASK 18 - 3-D batch slicing (batch, seq, dim)
#
# Write batch_slice(X): X is (2, 4, 3). Return:
#   last: X[:, -1, :] -> (2, 3) last token of each sequence
#   first_two: X[:, :2, :] -> (2, 2, 3)
#   one_vec: X[1, 2, :] -> (3,) single token vector
#
# Why: Stage 3 done-when is reading (1, 18, 512) + x[:, -1, :].


def batch_slice(X):
    ...


X = np.arange(24).reshape(2, 4, 3)
out = batch_slice(X)
assert out["last"].shape == (2, 3)
assert np.array_equal(out["last"][0], X[0, -1, :])
assert out["first_two"].shape == (2, 2, 3)
assert out["one_vec"].shape == (3,)
assert np.array_equal(out["one_vec"], X[1, 2, :])
print("Task 18 passed")

In [ ]:
# TASK 19 - 3-D transpose + batched scores (Q @ K.T)
#
# Write swap_last(X): X is (b, m, n) -> (b, n, m) via transpose(0, 2, 1).
# Write bscores(Q, K): Q (2, 3, 4), K (2, 5, 4) -> Q @ K.transpose(0, 2, 1) = (2, 3, 5).
#
# Why: every attention layer does exactly bscores on (batch, seq, head_dim).


def swap_last(X):
    ...


def bscores(Q, K):
    ...


X = np.arange(24).reshape(2, 3, 4)
assert swap_last(X).shape == (2, 4, 3)
Q = np.arange(24).reshape(2, 3, 4).astype(float)
K = np.arange(40).reshape(2, 5, 4).astype(float)
S = bscores(Q, K)
assert S.shape == (2, 3, 5)
assert np.isclose(S[0, 0, 0], 14.0)
print("Task 19 passed")

In [ ]:
# TASK 20 - Norms + cosine similarity
#
# Write l2(v): scalar sqrt(sum(v**2)). Write cos(a, b): dot / (l2(a)*l2(b)).
#
# Why: LayerNorm intuition + cosine is dot on normalized vectors.
# Shapes: (d,) + (d,) -> scalar.


def l2(v):
    ...


def cos(a, b):
    ...


assert np.isclose(l2(np.array([3.0, 4.0])), 5.0)
assert np.isclose(cos(np.array([1.0, 0.0]), np.array([0.0, 1.0])), 0.0)
assert np.isclose(cos(np.array([1.0, 1.0]), np.array([1.0, 1.0])), 1.0)
print("Task 20 passed")

In [ ]:
# TASK 21 - Log-softmax (stable)
#
# Write log_softmax(x): 1-D -> 1-D, x - max - log(sum(exp(x - max))).
#
# Why: CE on logits uses this, not softmax then log (underflow).
# Check: exp(out).sum() == 1, argmax preserved.


def log_softmax(x):
    ...


out = log_softmax(np.array([1.0, 2.0, 3.0]))
assert out.shape == (3,)
assert np.isclose(np.exp(out).sum(), 1.0)
assert out.argmax() == 2
assert out[2] > out[1] > out[0]
print("Task 21 passed")

In [ ]:
# TASK 22 - Causal mask + masked softmax (real attention step)
#
# Write causal_softmax(scores, pos): scores (seq,), pos int.
# Keep [:pos+1], set the rest to -1e9, then stable softmax.
#
# Why: decoder cannot look at future tokens. pos=1 sees 0,1 only.


def causal_softmax(scores, pos):
    ...


s = np.array([2.0, 1.0, 3.0, 0.0])
out = causal_softmax(s, 1)
assert out.shape == (4,)
assert np.isclose(out.sum(), 1.0)
assert out[0] > out[1] > out[2]
assert out[2] < 1e-6 and out[3] < 1e-6
print("Task 22 passed")

In [ ]:
# TASK 23 - Attention output = weights @ values
#
# Write attend(w, V): w (n,) sums to 1, V (n, d) -> (d,) weighted sum.
#
# Why: second half of attention. Scores -> weights -> mix the values.
# Shapes: (n,) @ (n, d) -> (d,).


def attend(w, V):
    ...


w = np.array([0.5, 0.3, 0.2])
V = np.array([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]])
out = attend(w, V)
assert out.shape == (2,)
assert np.allclose(out, np.array([0.7, 0.5]))
print("Task 23 passed")

In [ ]:
# TASK 24 - Shuffle + train/val split
#
# Write split_ids(n, val_frac, seed): permute 0..n-1 with RandomState(seed),
# split last val_frac part as val. Return (train_ids, val_ids).
#
# Why: every training loop shuffles then splits. Deterministic via seed.


def split_ids(n, val_frac, seed):
    ...


tr, va = split_ids(10, 0.2, 0)
assert len(tr) == 8 and len(va) == 2
assert set(tr.tolist()) | set(va.tolist()) == set(range(10))
assert set(tr.tolist()) & set(va.tolist()) == set()
tr2, va2 = split_ids(10, 0.2, 0)
assert np.array_equal(tr, tr2)
print("Task 24 passed")